GET http://localhost:3333/api/hello

###
GET http://localhost:3333/routes

###
GET http://localhost:3333/routes/seed

###
POST http://localhost:3333/routes
Content-Type: application/json

{
  "title": "minha rota",
  "startPosition": { "lat": 0, "lng": 1 },
  "endPosition": { "lat": 2, "lng": 3 }
}
